### ISSUE TITLE
Lambda "ets_get_cpu_frequency" and "ets_get_apb_freq" shows error

### ISSUE THREAD

**Issue by Bjk8kds** [esphome/issues#6570]
### The problem

In the previous version, everything was fine, the compilation was successful, but an error appeared in Esphome version 2024.12.0 when using the lambda function "ets_get_cpu_frequency" and "ets_get_apb_freq" to display CPU and APB speed.

### Which version of ESPHome has the issue?

2024.12.0

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

Core 2024.12.4

### What platform are you using?

ESP32-IDF

### Board

ESP32C3 Supermini, Xiao C3, S3 Mini

### Component causing the issue

ets_get_cpu_frequency, ets_get_apb_freq

### YAML Config

```yaml
sensor:
  - platform: template
    name: ESP CPU Speed
    icon: mdi:chip
    lambda: |-
      return ets_get_cpu_frequency();
    accuracy_decimals: 0
    unit_of_measurement: 'MHz'
    entity_category: "diagnostic"
  - platform: template
    name: ESP APB Speed
    icon: mdi:chip
    lambda: |-
      return ets_get_apb_freq() / 1000000;
    accuracy_decimals: 0
    unit_of_measurement: 'MHz'
    entity_category: "diagnostic"
```

### Anything in the logs that might be useful for us?

```txt
INFO ESPHome 2024.12.0
INFO Reading configuration /config/esphome/esp32c3-ld2410-presence.yaml...
WARNING GPIO8 is a strapping PIN and should only be used for I/O with care.
Attaching external pullup/down resistors to strapping pins can cause unexpected failures.
See https://esphome.io/guides/faq.html#why-am-i-getting-a-warning-about-strapping-pins
INFO Generating C++ source...
INFO Updating https://github.com/espressif/esp-protocols.git@mdns-v1.3.2
INFO Compiling app...
Processing esp32c3-ld2410-presence (board: lolin_c3_mini; framework: espidf; platform: https://github.com/pioarduino/platform-espressif32.git#51.03.07)
--------------------------------------------------------------------------------
HARDWARE: ESP32C3 160MHz, 320KB RAM, 4MB Flash
 - framework-espidf @ 3.50105.0 (5.1.5) 
 - tool-cmake @ 3.21.3 
 - tool-esptoolpy @ 4.8.1 
 - tool-mklittlefs @ 3.2.0 
 - tool-ninja @ 1.7.1 
 - tool-riscv32-esp-elf-gdb @ 12.1.0+20221002 
 - tool-xtensa-esp-elf-gdb @ 12.1.0+20221002 
 - toolchain-esp32ulp @ 2.35.0-20220830 
 - toolchain-riscv32-esp @ 12.2.0+20230208
Reading CMake configuration...
Warning! Flash memory size mismatch detected. Expected 4MB, found 2MB!
Please select a proper value in your `sdkconfig.defaults` or via the `menuconfig` target!
Dependency Graph
|-- ArduinoJson @ 6.18.5
Compiling .pioenvs/esp32c3-ld2410-presence/src/main.cpp.o
Archiving .pioenvs/esp32c3-ld2410-presence/esp-idf/console/libconsole.a
Compiling .pioenvs/esp32c3-ld2410-presence/cxx/cxx_exception_stubs.cpp.o
Compiling .pioenvs/esp32c3-ld2410-presence/cxx/cxx_guards.cpp.o
Archiving .pioenvs/esp32c3-ld2410-presence/esp-idf/cxx/libcxx.a
Compiling .pioenvs/esp32c3-ld2410-presence/driver/gpio/gpio.c.o
Compiling .pioenvs/esp32c3-ld2410-presence/driver/gpio/gpio_glitch_filter_ops.c.o
Compiling .pioenvs/esp32c3-ld2410-presence/driver/gpio/rtc_io.c.o
Compiling .pioenvs/esp32c3-ld2410-presence/driver/spi/spi_bus_lock.c.o
Compiling .pioenvs/esp32c3-ld2410-presence/driver/deprecated/adc_legacy.c.o
Compiling .pioenvs/esp32c3-ld2410-presence/driver/deprecated/adc_dma_legacy.c.o
Compiling .pioenvs/esp32c3-ld2410-presence/driver/gpio/dedic_gpio.c.o
Compiling .pioenvs/esp32c3-ld2410-presence/driver/gpio/gpio_pin_glitch_filter.c.o
Compiling .pioenvs/esp32c3-ld2410-presence/driver/gptimer/gptimer.c.o
/config/esphome/esp32c3-ld2410-presence.yaml: In lambda function:
/config/esphome/esp32c3-ld2410-presence.yaml:184:14: error: 'ets_get_cpu_frequency' was not declared in this scope
  184 |       return ets_get_cpu_frequency();
      |              ^~~~~~~~~~~~~~~~~~~~~
Compiling .pioenvs/esp32c3-ld2410-presence/driver/gptimer/gptimer_priv.c.o
/config/esphome/esp32c3-ld2410-presence.yaml: In lambda function:
/config/esphome/esp32c3-ld2410-presence.yaml:192:14: error: 'ets_get_apb_freq' was not declared in this scope
  192 |       return ets_get_apb_freq() / 1000000;
      |              ^~~~~~~~~~~~~~~~
Compiling .pioenvs/esp32c3-ld2410-presence/driver/deprecated/timer_legacy.c.o
Compiling .pioenvs/esp32c3-ld2410-presence/driver/i2c/i2c.c.o
*** [.pioenvs/esp32c3-ld2410-presence/src/main.cpp.o] Error 1
========================= [FAILED] Took 63.25 seconds =========================
```

**Comment by randybb** [comment]
since it is not esphome function, it must be related to esp-idf since esphome swiched from 4.4 to 5.1 

you can try use that include in your lambda. this should fix it for both
https://github.com/espressif/esp-idf/issues/10191

**Comment by Bjk8kds** [comment]
> since it is not esphome function, it must be related to esp-idf since esphome swiched from 4.4 to 5.1
> 
> you can try use that include in your lambda. this should fix it for both [espressif/esp-idf#10191](https://github.com/espressif/esp-idf/issues/10191)

How to do it? Is it like this?
```
    lambda: |-
      #include "rom/ets_sys.h"

      return ets_get_cpu_frequency();
```
Error still occurs during compilation.

Tried adding `ets_sys.h` file with this code, I don't know which file is the correct one, tried the file I got from the web, in the Esphome directory, error still appears because the file also has other `include`.
```
esphome:
  ...
  includes: ets_sys.h
```
Honestly, I'm a novice and don't know how to show CPU speed other than the usual code `ets_get_cpu_frequency()`.

**Comment by randybb** [comment]
I thought I have seen it somewhere as a working solution, well, then probably only an esternal component....

Unfortunately, esphome includes is taking only files in the config directory.

Checking discord and for the frequency `return arch_get_cpu_freq_hz();` might work ([src](https://esphome.io/api/namespaceesphome#a7fab17a487ad7c3b6ea142be91f0d52f))

**Comment by Bjk8kds** [comment]
> I thought I have seen it somewhere as a working solution, well, then probably only an esternal component....
> 
> Unfortunately, esphome includes is taking only files in the config directory.
> 
> Checking discord and for the frequency `return arch_get_cpu_freq_hz();` might work ([src](https://esphome.io/api/namespaceesphome#a7fab17a487ad7c3b6ea142be91f0d52f))

Nah, the library is confusing (mistype?)
Why `arch_get_cpu_freq_hz()` "cpu freq" return `rtc_clk_apb_freq_get()` "apb freq", aren't those 2 different things?

**Comment by randybb** [comment]
I guess we can fix it :)
