### ISSUE TITLE
LD2420 sensor data 'Unknown' on ESP32-C3/S3 after update 2025.6.3

### ISSUE THREAD

**Issue by NH-Networks** [esphome/issues#7195]
### The problem

Working fine on 2025.6.2 and maybe related to #7163 ?

### Which version of ESPHome has the issue?

2025.6.3

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP32-IDF

### Component causing the issue

LD2420 UART

### YAML Config

```yaml
uart:
  tx_pin: GPIO2
  rx_pin: GPIO3
  baud_rate: 115200
  parity: NONE
  stop_bits: 1

ld2420:
```

### Anything in the logs that might be useful for us?

```txt
"LD2420 firmware version v0. 0.0 and older are only supported in simple mode. "
"Component ld2420 is marked FAILED"
```

**Comment by rgnyldz** [comment]
I have the same issue several different ESP devices (especially C6, S3 on esp-idf). After I do OTA the ld2420 fails. I have to disconnect and connect  power in order for it to work.

**Comment by tarlen** [comment]
I'm also experiencing the same issue, with both Arduino and ESP-IDF platforms, ESP32-S2. Unfortunately mine are not in a location that is easy to power-cycle.

**Comment by dpkmi** [comment]
Has anybody been able to resolve this issue? I have 3 presence sensors that are not working. Can't figure out what is wrong

**Comment by Luccos** [comment]
Same problem on ESP32C3 and ESP32 WROOM, after installation you have to disconnect the power and reactivate it for it to work.

**Comment by martinmuszio** [comment]
From brief experience with these devices, I believe the problem lies in the OTA reset of esphome, regardless of the esphome version, when it restarts via OTA the radar MCU can no longer communicate with our ESP, there is only a hard reset left, so that the radar can initialize again, for those who have the radar permanently powered I suggest a P channel mosfet for high side switching (IRLML6402 or AO3407A) and to turn on the LD2040 every time it restarts via soft

**Comment by listlesslife** [comment]
I'm having the same issue with an esp32 mini and an ld2410 after updating to 2025.8.0. I was able to get it to work again by power cycling, but it then reverted to 2025.6.3. I then updated to 2025.8.0 via serial (which the device retained), and again all of the ld2410 entities are showing "Unknown." 

I have lots of other devices using different boards that are working as expected.

**Comment by dpkmi** [comment]
I ditched all the ld2420's. And got me some ld2410c instead. Now those are all working fine now.

**Comment by rgnyldz** [comment]
With the last Esphome Update some of my devices now do work after OTA. But other do still give this issue. Maybe this is related to the improvements done to ram/flash management. Not sure.

**Comment by Luccos** [comment]
"P channel mosfet for high side switching (IRLML6402 or AO3407A) and to turn on the LD2040 every time it restarts via soft" ?can you explain better, thanks

**Comment by martinmuszio** [comment]
"P channel mosfet for high side switching (IRLML6402 or AO3407A) and to turn on the LD2040 every time it restarts via soft" ?can you explain better, thanks
summary:
3V3 ----(Source) P-MOSFET (Drain)----> VCC LD module
             |
           (Gate)
             +-- 100 kΩ -- a 3V3     (pull-up: keeps off by default)
             |
           100 Ω
             |
           GPIO ESP32                 (LOW = turn on module, HIGH = turn off )

then in yaml:
switch:
  - platform: gpio
    id: ld_power
    pin:
      number: GPIO25
      inverted: true       # 0V turn on LD2040

script:
  - id: reset_ld
    then:
      - switch.turn_off: ld_power   # Gate=HIGH -> TURN OFF LD2040
      - delay: 1s
      - switch.turn_on: ld_power    # Gate=LOW  -> TURN ON LD2040
      - delay: 2s

esphome:
  on_boot:
    priority: -100
    then:
      - script.execute: reset_ld

more info about high side switch:
https://hackaday.com/2015/09/16/learn-and-build-a-high-side-switch/

**Comment by Luccos** [comment]
Ah OK, so you're saying that it's enough to just disconnect the LD2040 from the power supply? I thought it was necessary to remove the +5V from the ESP32, I tried to create a switch with an opto and a P-MOS that would disconnect the +5V from the power supply via a command from GPIO0 for a fraction of a second but it wasn't enough, ok I'll try again using your advice, Thanks

**Comment by snippem** [comment]
Hello everyone,
Up until now, my ESP32-C3 has always worked perfectly with an LD2420. Unlike the ESP32S3, which I have to power down every time after an update. Only with the latest version of ESP-Home does the ESP32-C3 no longer work at all with an LD2420. It always reads firmware version 0.0.0, and that's it.

when I add this.

esphome:

name: living-room-movement

friendly_name: Living-room-movement

esp32:

board: esp32-c3-devkitc-02

framework:

type: esp-idf

version: "5.3.1"

platform_version: 6.9.0

The ESP32-C3 is working properly again. I'm not an expert myself, but maybe someone has an idea. (And maybe for the ESP32-S3 too, haha)

FYI:
What I've done so far:
Reinstalling via USB had no effect. Reconfiguring according to ESP-home documentation with an LD2420 without any additional components had no effect. Adding it as a new node according to ESP-home documentation with an LD2420 also no effect.
(Same goes for the ESP32-S3 only difference this one detects the LD2420 after a powercycle)

**Comment by rgnyldz** [comment]
<img width="3442" height="1827" alt="Image" src="https://github.com/user-attachments/assets/e4608de0-7368-43f4-9a3b-24ab72cc4291" />

This is getting out of hand, the red lines indicate the failed ld2420 chips after OTA. 

I did not update the kids room because they are sleeping and the device makes a chime when connected but that will fail also.

Boards are different boards. ESP32-S3, esp32 d1, esp32-c6, mixed esp-idf and arduino framework.

**Comment by j-shirazi** [comment]
Hi,
I have the same problem after OTA or "ESP soft/hard reset"! Only works after the power is disconnected and then reconnected.
My boards are ESP32-S3 and ESP32-C3, and I use the ESP-IDF and Arduino frameworks with the same results.
LOG: "LD2420 firmware version v0. 0.0 and older are only supported in simple mode. "
"Component ld2420 is marked FAILED" 
ESPHome: 2025.9.1

**Comment by geekmystique** [comment]
Same here, used to work but funnily enough they sometimes came back to life on newer Esphome releases. It must be some communication issue. Power cycling does not fix it, neither does setting baud_rate to 0 on logger to avoid serial conflicts.

[18:26:17.097][W][ld2420:211]: Firmware version v0.0.0 and older supports Simple Mode only
[18:26:17.099][E][component:154]:   ld2420 is marked FAILED: unspecified

```
uart:
  id: ubus
  tx_pin: GPIO7  # Change based on your wiring
  rx_pin: GPIO6  # Change based on your wiring
  baud_rate: 115200  # Use 256000 for firmware < v1.5.3
  parity: NONE
  stop_bits: 1   

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino



ld2420: 
```


Same on idf framework.

Update: One more thought: Are we sure this is a software problem with the device - is the chip burning out after time? I have rolled back one device to 2025.4 and it still did not come back to life. Or do i still use newer libraries which might be to blame when i compile with an older Esphome release?

**Comment by VitalyIak** [comment]
LD2420 - same issue. after OTA - have the same problem, as described at this thread.

**Comment by RandallHW** [comment]
I have been wresting with this same problem for too many days now and I only have a temporary work around. In my case I usually use esp32-c6 and connect an ld2420 and a bme680 to have environmental/presence sensors around the house.  Never a problem.  Then I decided a panel would be nice for a bedside clock/sensor and so bought the waveshare esp32-s3-touch-7 and connected the same sensors.  After a day or so the ld2420 starts acting up, not right away because a brand new ld2420 works well for a couple days but then it starts failing (component disabled) more and more often on resets and power cycles, until it never comes up.  It is not the ld2420 itself though because I can transfer that same sensor to an esp32-c6 and it is rock solid again.
I turned debug on the esp32-s3 UART and I can see that the UART works and the ld2420 works because it is sending packets, but the ld2420 component has already been disabled early on and so it is ignored.  So it seems that the ld2420 is in a garbage state early when the esp boots up.  Anyway, keeping the display off during boot (in case it is a power bump thing) and then adding this delay and reconfig in the boot sequence seems to help a lot.   If it still doesn't come up after a power cycle, it sometimes comes up after a reset, and if it still doesn't come up then unplug and plug in the ld2420 gnd pin and then a reset makes it always come back up.  Not great, but a lot better than before.  It seems to be in a garbage state when the esp polls for it and I understand the esp32-c6 boots slower than the s3 and so maybe that is why my c6's all work much better with this sensor.

esphome:
  name: esp-panel
  friendly_name: ESP-Panel
  platformio_options:
    build_flags: "-DBOARD_HAS_PSRAM"
  on_boot:
    priority: -100
    then:
      - delay: 2s                                 # Wait for screen and WiFi to stabilize
      - uart.write: [0xFF, 0xFF, 0xFF, 0xFF]      # Sending dummy high bytes to clear the line
      - logger.log: "UART Bus cleared. Waiting for initialization."
      - lambda: |-
          id(my_ld2420).setup();                  // Re-run the setup routine
      - delay: 3s 
      - switch.turn_on: lcdbacklight 
      - logger.log: "Power stabilized. Backlight active."
          
psram:
  mode: octal
  speed: 80MHz
esp32:
  board: esp32-s3-devkitc-1
  variant: ESP32S3
  flash_size: 8MB
  framework:
    type: esp-idf

logger:
  level: DEBUG
  baud_rate: 0

I know it is not a real solution, but it seems to help.

Update - It has been a couple days and at least a dozen reboots/reflashes since I put the on_boot delay code section in there and the ld2420 hasn't failed to come up once!  This fixed it for me.

**Comment by prokudin07** [comment]
The same problem. 
Solved with add the next code:
```
external_components:
  - source: github://esphome/esphome@2025.10.5
    components: [uart]
```

**Comment by rgnyldz** [comment]
> ```
> external_components:
>   - source: github://esphome/esphome@2025.10.5
>     components: [uart]
> ```

Tried this, did not help. Sensor still not working after OTA and stil getting the below log.

```
[22:48:47.909][W][ld2420:212]: Firmware version v0.0.0 and older supports Simple Mode only
[22:48:47.911][E][component:230]:   ld2420 is marked FAILED: unspecified
```

**Comment by VitalyIak** [comment]
So, I bought counterfeit product and its looks like original one, but doesn't support real protocol from HiLink. You can try to connect via windows tool, or just as telnet... counterfeit product send just asci string like distance ....  And speed is 115200. Unfortunately I bought not original product, be careful!  All elements at board absolutely same!

**Comment by rgnyldz** [comment]
I was able to fix this by adding a dummy uart to my code like below;

```
uart:
  - rx_pin: 15
    baud_rate: 9600
    id: dummy_uart
  - tx_pin: GPIO17
    rx_pin: GPIO18
    baud_rate: 115200
    parity: NONE
    stop_bits: 1
    id: ld2420_uart

ld2420:
  uart_id: ld2420_uart

... [rest of the code]
```

after adding this my code the ld2420 is working all fine after OTA. 

Hope this helps anyone else.
